
package com.payamak.panel.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 */
@WebService(name = "SendSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSoap {


    /**
     * @param password
     * @param from
     * @param to
     * @param text
     * @param isflash
     * @param username
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SendSimpleSMS2", action = "http://tempuri.org/SendSimpleSMS2")
    @WebResult(name = "SendSimpleSMS2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSimpleSMS2", targetNamespace = "http://tempuri.org/", className = "com.payamak.panel.client.SendSimpleSMS2")
    @ResponseWrapper(localName = "SendSimpleSMS2Response", targetNamespace = "http://tempuri.org/", className = "com.payamak.panel.client.SendSimpleSMS2Response")
    String sendSimpleSMS2(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
            String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
            String password,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
            String to,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
            String from,
        @WebParam(name = "text", targetNamespace = "http://tempuri.org/")
            String text,
        @WebParam(name = "isflash", targetNamespace = "http://tempuri.org/")
            boolean isflash);

}
